#!/usr/bin/env bash
mkdir -p dist
echo "build src/pdmaptw.ls -> dist/pdmaptw.js ..."
./node_modules/.bin/lsc -cbp src/pdmaptw.ls > dist/pdmaptw.js
echo "minifying pdmaptw.js ..."
./node_modules/.bin/uglifyjs dist/pdmaptw.js > dist/pdmaptw.min.js
echo "deploy into local web ..."
mkdir -p web/static/assets/lib/pdmaptw/
cp -R dist/* web/static/assets/lib/pdmaptw/
echo "done."
