#!/usr/bin/env bash

rm -rf download/county download/town download/village
mkdir -p download/county
mkdir -p download/town
mkdir -p download/village

# county - https://data.gov.tw/dataset/7442
echo "fetching county files..."
wget -O download/county/shp.zip "http://data.moi.gov.tw/MoiOD/System/DownloadFile.aspx?DATA=72874C55-884D-4CEA-B7D6-F60B0BE85AB0"
cd download/county; unzip shp.zip; cd ../..

# town - https://data.gov.tw/dataset/7442
echo "fetching town files..."
wget -O download/town/shp.zip "http://data.moi.gov.tw/MoiOD/System/DownloadFile.aspx?DATA=CD02C824-45C5-48C8-B631-98B205A2E35A"
cd download/town; unzip shp.zip; cd ../..

# village - https://data.gov.tw/dataset/7438
echo "fetching village files..."
wget -O download/village/shp.zip "http://data.moi.gov.tw/MoiOD/System/DownloadFile.aspx?DATA=B8AF344F-B5C6-4642-AF46-1832054399CE"
cd download/village; unzip shp.zip; cd ../..
